---
name: Test Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/sdre.yml
    name: "Build & Push Latest"
    with:
      push_enabled: true
      ghcr_repo_owner: mikenye
      ghcr_repo: ${{ github.repository }}
      build_latest: true
      build_baseimage_test: false

    secrets:
      ghcr_token: ${{ secrets.GITHUB_TOKEN }}

  build_test:
    uses: ./.github/workflows/sdre.yml
    name: "Build & Push Test"
    with:
      push_enabled: true
      ghcr_repo_owner: mikenye
      ghcr_repo: ${{ github.repository }}
      build_latest: false
      build_test: true
    secrets:
      ghcr_token: ${{ secrets.GITHUB_TOKEN }}

  build_baseimage_test:
    uses: ./.github/workflows/sdre.yml
    name: "Build & Push Test base image"
    with:
      push_enabled: true
      ghcr_repo_owner: mikenye
      ghcr_repo: ${{ github.repository }}
      build_latest: false
      build_baseimage_test: true
      # should not change anything, but why not
      build_baseimage_url: :acars-decoder-soapy/:acars-decoder-soapy-test-pr

    secrets:
      ghcr_token: ${{ secrets.GITHUB_TOKEN }}

  populate_cache:
    name: "Populate cache"
    runs-on: ubuntu-22.04
    steps:
      # Check out code
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: "Make some data to cache"
        run: |
          mkdir -p ./cache
          dd if=/dev/zero of=./cache/data bs=4k count=50
          ls -la ./cache/data

      # Populate cache
      - name: "Populate cache"
        id: populate_cache
        uses: actions/cache@v4.2.4
        with:
          path: ./cache
          key: ${{ github.run_id }}

  check_cache:
    name: "Check cache"
    needs: [populate_cache]
    uses: ./.github/workflows/sdre.yml
    with:
      push_enabled: false
      build_latest: true
      ghcr_repo_owner: mikenye
      ghcr_repo: ${{ github.repository }}
      cache_enabled: true
      cache_path: ./cache
      cache_key: ${{ github.run_id }}
    secrets:
      ghcr_token: ${{ secrets.GITHUB_TOKEN }}
