---
name: Test Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  test_build_only:
    uses: ./.github/workflows/build_and_push_image.yml
    with:
      push_enabled: false
      ghcr_repo_owner: ${{ github.repository_owner }}
      ghcr_repo: ${{ github.repository }}
      platform_linux_arm32v6_enabled: true
      platform_linux_i386_enabled: true
      build_nohealthcheck: false
    secrets:
      ghcr_token: ${{ secrets.GITHUB_TOKEN }}

  test_build_push:
    uses: ./.github/workflows/build_and_push_image.yml
    with:
      push_enabled: true
      ghcr_repo_owner: ${{ github.repository_owner }}
      ghcr_repo: ${{ github.repository }}
      platform_linux_arm32v6_enabled: true
      platform_linux_i386_enabled: true
      build_nohealthcheck: false
    secrets:
      ghcr_token: ${{ secrets.GITHUB_TOKEN }}

  test_build_only_nohealthcheck:
    uses: ./.github/workflows/build_and_push_image.yml
    with:
      push_enabled: false
      ghcr_repo_owner: ${{ github.repository_owner }}
      ghcr_repo: ${{ github.repository }}
      platform_linux_arm32v6_enabled: true
      platform_linux_i386_enabled: true
    secrets:
      ghcr_token: ${{ secrets.GITHUB_TOKEN }}

  test_build_push_nohealthcheck:
    uses: ./.github/workflows/build_and_push_image.yml
    with:
      push_enabled: true
      ghcr_repo_owner: ${{ github.repository_owner }}
      ghcr_repo: ${{ github.repository }}
      platform_linux_arm32v6_enabled: true
      platform_linux_i386_enabled: true
    secrets:
      ghcr_token: ${{ secrets.GITHUB_TOKEN }}
